name: 'Deploy Dev'

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  site:
    name: 'Deploy site'
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build site
      run: rm -rf dist && cp -r client/. dist
      working-directory: ./

    - name: Deploy site
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: aws s3 sync dist s3://havesomecode-landing-site-bucket--stage-dev
      working-directory: ./
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
